givedirectly/Google-Partnership

docs/layer_util.js

Now: 
This doesn't really fix #174, but it makes ImageCollection a lot more palatable, if we can handle the lag.

Mask ImageCollection to avoid jagged black edges

---

cypress.json
cypress/integration/integration_tests/checkbox_test.js
cypress/integration/integration_tests/click_feature_test.js
cypress/integration/integration_tests/highlight_features_test.js
cypress/integration/integration_tests/polygon_draw_test.js
cypress/integration/integration_tests/sidebar_test.js
cypress/integration/integration_tests/update_test.js
cypress/plugins/index.js
cypress/support/script_loader.js

If the baseUrl is not set, then Cypress runs beforeEach hooks twice (https://github.com/cypress-io/cypress/issues/2636), which left lingering data.
With that fix, the belt-and-suspenders approach is mostly unnecessary, but added it for good measure: make the test directory start with the start date of the test and at the start of each test, delete all directories older than 24 hours. Unfortunately, Firestore has a nasty quirk: a document will only show up in its parent collection's listing if it has fields of its own, transitive fields don't count. So we add a dummy field to the root test document that we create, so that they show up in listings later.
This last part is obviously pretty hacky, and perhaps we don't actually need it with the root bug fixed. But I do worry about GiveDirectly …

Fix deletion of test data from Firestore

---

cypress/integration/integration_tests/polygon_draw_test.js
cypress/integration/unit_tests/polygon_draw_test.js
docs/create_map.js
docs/polygon_draw.js

Most of these tests don't need to be integration tests. Starting with this one, since it's pretty flaky.
Setting an attribute on the event in overlaycomplete is a bit hacky. I can deduce when the promise is finished other ways as well, but since that promise is exactly what we want, I think it's nice to use it. Other alternatives would be to wait on the firebase add to complete (we can track that, since we're stubbing out the add), or to watch for the loading waiter changes (right now we completely stub those out).
The interaction between Cypress and Promises isn't my favorite, but not too terrible.

Deflake test by making it a unit test

---

docs/layer_util.js

In the case that the Firebase fetch is slow, firebaseLayers may not be initialized, but that shouldn't block the score from being displayed. I don't know if this is responsible for our flaky loading-forever issues on Travis, but it seems possible.

Special-case score rather than relying on it not being in firebaseLayers

---

cypress/integration/unit_tests/checkbox_test.js
cypress/integration/unit_tests/style_functions_test.js
docs/create_map.js
docs/firebase_layers.js
docs/layer_util.js
docs/run.js

Using asset names like this has a few disadvantages:
1. Not all assets have obvious names (map tiles, for instance).
2. We might want to treat the same FeatureCollection as two different layers in the future (say, pull a different property from it for each layer).
3. A fundamental property we want, that assets have unique indices, is not enforced by design in our data structure.
4. Having a global map (needed for looking up asset names) is a code smell.
Instead, using indices everywhere we can. This lets us get rid of the global firebaseLayers object entirely, which is nice. Also this spurs some clean-ups/restructurings in layer_util.js.
We need to pass the actual Firestore data object into toggleLayerOn, which makes me a little sad, but it's ok. (I think in the future we might want to …

Stop using asset names as keys for layer metadata

---

docs/authenticate.js

For now, all this PR adds is snackbar notifications indicating that there was an error in authentication and leaves the details in the console.
I'm definitely open to ideas on improving this further.

Adding UI notifications for authentication errors

---

cypress/integration/unit_tests/checkbox_test.js
cypress/integration/unit_tests/polygon_draw_test.js
cypress/support/callback_latch.js
docs/layer_util.js

Three main changes in this PR:
1. Re-use the computed LayerDisplayData.overlay on toggle on, rather than making another call to EarthEngine. I think this got lost in the shuffle of switching to deck and then adding overlay back, and it's been gone for a while.
1. If there is a pending promise in toggleOn, don't do anything. The promise will see that it should display the layer whenever it finishes. Before this change, if an EE request was taking a long time, rapidly toggling a checkbox on and off would add more and more EE requests.
1. Start the loading indicator for map images on EE computation, not on tile rendering.
Test changes:
1. Add tests for the above functionality.
1. Return Promises all the way out from layer_util.js, for easier testing.
1. Add a regression test for score layer …

Improve layer_util: cache EE results, start loading indicator earlier

---

docs/firestore_document.js
docs/resources.js

This is an incompatible change. I renamed the EarthEngine folders to have the right form and modified Firestore data to point to the new assets.
Most of the work in resources.js is wasted, because we'll be deleting it in favor of Firestore-based disaster metadata retrieval, but whatever.

Change disaster name to include the year

---

docs/import/add_disaster.js
docs/import/add_disaster_startup.js

Have unconditional use of jQuery happen only in add_disaster_startup.js.

Fix add_disaster_test

---

cypress/integration/integration_tests/checkbox_test.js
cypress/integration/integration_tests/polygon_draw_test.js
cypress/integration/unit_tests/checkbox_test.js
cypress/integration/unit_tests/polygon_draw_test.js
cypress/support/test_map.js
docs/composite_image_map_type.js
docs/firebase_layers.js
docs/layer_util.js
docs/run.js
docs/test_utils/empty.html

NOAA imagery is available as map tiles, which avoids the issue of having to upload images to EarthEngine. Because the user will want to view/hide all the tiles as a set, we implement our own custom CompositeImageMapType, similar to ImageMapType, but able to handle a collection of URLS. It fetches all of them, and for all the ones that returned images, stacks them on top of each other and displays the whole stack (inside a div).
We render images as they come in, cancel pending fetches if the tile is no longer relevant, and gracefully retry rate-limited requests.
I've added a map tile asset in the new "layers" array in Firestore, and switched to using "layers" in this PR. It's not a huge problem if we switch to using "layers" before this PR goes in: there will be a console error if you try …

Support collections of map tile URLS as layers

---

cypress/integration/unit_tests/polygon_draw_test.js
docs/polygon_draw.js
docs/resources.js
docs/run.js

Disasters are going to be retrieved live from Firestore, not hard-coded in resources.js, so we can't really depend on this data.
Also make our map tolerant to a missing damage layer. After this, if import_data produces a "score" asset with no damage, our map should work as expected.

Remove calls to getResources()

---

cypress/integration/unit_tests/add_disaster_test.js
cypress/integration/unit_tests/style_functions_test.js
docs/README.md
docs/firebase_layers.js
docs/import/add_disaster.js
docs/import/add_disaster_util.js
docs/import/color_function_util.js

This will allow up to store more than one schema if the user is switching back and forth between color schemas. 
Along the way, rename STATE -> State to keep with other enums we've created. Also, section out a new color function file and a util file for add disaster because it's getting big and will probably continue to grow.

Explicitly store color schema choice in firestore

---

cypress/integration/unit_tests/add_disaster_test.js
cypress/integration/unit_tests/checkbox_test.js
cypress/integration/unit_tests/style_functions_test.js
docs/README.md
docs/firebase_layers.js
docs/import/color_function_util.js

We have an explicit current schema field now so we don't need these to be separate. This also means if a user is switching between continuous and single the property gets reused across the different schemas.

Combine 'single-color' and 'base-color' fields in firestore

---

cypress/integration/integration_tests/polygon_draw_test.js
cypress/integration/unit_tests/add_disaster_test.js
cypress/integration/unit_tests/center_test.js
cypress/integration/unit_tests/import_data_test.js
cypress/support/firestore_map_bounds.js
cypress/support/script_loader.js
docs/import/import_data.js
docs/resources.js

We were kicking off the Firestore fetch without waiting for anything. ~I still don't understand how that fetch could see data from a different test case (because we wipe data between tests), but~ 
What we were doing before was clearly wrong on two levels: we weren't waiting for the write to complete, and we were doing the read in program order, not Cypress order. Fixed both of those, with not too bad a hack on the first side, I hope.
Also, we weren't actually doing any proper setup in import_data_test for Firebase, which explains why the data was sticking around. Fixed that. We didn't need to do proper setup because I had apparently made the database global read-write during testing and forgotten to restrict it. I've tested with the restriction (it works) and undone it for now. Will …

Fix import data test

---

docs/popup.js

This is actually a bug in production, though a very hard one to hit. We were assuming that by the time the calculated data for a polygon was ready, the popup's html was created. However, the popup's html is normally created in onAdd, called by the Google Map, which happens in a separate thread from popup creation (verified with console debug statements). Thus, it is possible for the calculated data task to complete and try update calculated data before the div is present. Tolerate that situation: when the div is created, it will be initialized to the proper value in createPopupHtml() anyway.

Partially deflake polygon_draw_test

---

cypress/integration/unit_tests/manage_disaster_test.js
cypress/integration/unit_tests/manage_layers_test.js
docs/import/list_ee_assets.js
docs/import/manage_disaster.js

Create EE folders for both the disaster and the relevant states.  Wait to automatically toggle to new disaster (or let new disaster appear in picker) until these things have finished.

write disaster folder on new disaster write

---

cypress/integration/unit_tests/color_function_util_test.js
docs/import/color_function_util.js

We now always initialize an empty colors map during (FC) layer creation so we don't need these anymore.

Remove guards around colors map

---

cypress/integration/unit_tests/manage_disaster_test.js
docs/import/manage_disaster.js

This improves error messaging to users when the stored value is not displayed in the select (because, for instance, the user deleted an asset after previously selecting it here).
Note that if the user then re-creates the asset, they'll have to reload the page, but that seems ok.
We don't overwrite the value in Firestore, even though it's not valid, until the user changes it manually, to avoid the user losing data if an asset is momentarily not there (because they're deleting and recreating it).

Validate values of select rather underlying data

---

docs/authenticate.js

We have clang v7 on Travis, but Google style has apparently changed since then. Running multiple versions of clang on my Mac, I found that the choice of whether to put a space between the comment and the parameter name seems different for v7 and v9. Removing the `=` sign seems to stop the clash.

Change parameter comments that are making clang fight with itself

---

cypress/integration/unit_tests/manage_disaster_test.js
docs/firebase_layers.js
docs/import/center.js
docs/import/create_score_asset.js

Run SVI, median income, snap and total pop values through a parser while creating the score asset. The parser takes care of values like "250,000+" (250000) and non-numerics (null). Also make null values transparent for layer creation. 
closes #269

Be smarter about parsing number values during score asset creation

---

cypress/integration/unit_tests/create_score_asset_test.js
cypress/support/firestore_map_bounds.js
docs/import/create_score_asset.js

The damage envelope can slice through a block group (especially if the block group is large), so just use the Join's implicit filtering on block groups to avoid dealing with buildings we don't want.
Tests were already pointing to this being an issue, should have thought more about it. Getting rid of the scaling in the tests seems to expose some EE inaccuracies, so had to loosen our floating-point checks to compensate.

Don't filter by damage bounds when counting buildings

---

cypress/integration/unit_tests/manage_disaster_set_score_parameters_test.js
docs/import/manage_disaster.js

SVI and Income are always optional, Buildings optional when damage asset not present. Messaging stays in the button. We change the button color to a grayish yellow when missing optional assets.

Make SVI/Income/Buildings optional when possible

---

cypress.json
cypress/integration/unit_tests/manage_disaster_set_score_parameters_test.js
cypress/integration/unit_tests/score_bounds_map_test.js
cypress/support/import_test_util.js
cypress/support/script_loader.js
docs/basic_map.js
docs/import/manage_disaster.js
docs/import/score_bounds_map.js

Use EE TIGER states resource. Not instant, so we don't zoom if user manages to beat us to a zoom.
It might have been nice to cancel our operation if user panned as well, but I don't know how to get that event: bounds_changed fires too often. Also, if the user is panning around the map but it's zoomed out, probably not much value in it.
There is a weird quirk right now: if you switch between two disasters, and the second one doesn't have a polygon, we won't re-center the map until the state ee processing is finished. Until then, the previous disaster's map will stay up (though without the polygon). We could re-center the map on the US until the ee promise finished, but that felt pretty manic.
#283

Zoom to disaster states in map when polygon coordinates absent

---

cypress.json
cypress/integration/integration_tests/nav_test.js
cypress/integration/unit_tests/click_feature_test.js
cypress/integration/unit_tests/create_score_asset_test.js
cypress/integration/unit_tests/polygon_draw_test.js
cypress/integration/unit_tests/process_joined_data_test.js
cypress/integration/unit_tests/run_test.js
cypress/support/script_loader.js
docs/import/create_score_asset.js
docs/polygon_draw.js
docs/process_joined_data.js
docs/resources.js
docs/run.js
docs/script.js
docs/update.js

And use that backup if the new one is not found. We do this by catching a failure in our score promise and substituting the backup if the failure seems to be from a missing asset.
This works out because we don't do any processing of the score asset except via that promise. Stern comment added to that effect.
Test has a horrible wait because of an apparent Cypress bug (https://github.com/cypress-io/cypress/issues/5980).

Back up previous version of score asset when creating new one

---

cypress/plugins/index.js

This might help when a setup/teardown failure in one test case brings down Cypress for the rest of its lifetime, although not positive that a Cypress timeout will actually make the finally handler run. Can't hurt, though, and is definitely cleaner.

Use finally when deleting Firestore apps in plugins

---

docs/authenticate.js
docs/import/manage_disaster.html
docs/import/manage_layers.html
docs/index.html
docs/style.css

Show a dialog telling them how to whitelist themselves for EarthEngine, and send them to sign in again, hopefully this time as a whitelisted user. This provides a good hook for future work to catch errors and get a token from a server.
We use jQuery for this dialog because it offers clickable hyperlinks. There's some visual inconsistency because the other alert (for not being the gd user) is a standard html alert. I like the standard one better because we don't actually want the page to be usable/continue loading while it is up, but what to do.
Can be manually tested by going to our map page as a non-EE-whitelisted user.
Drive-by fix suggested by IntelliJ for the background-color attribute of .header-cell.
#340

Handle EE authentication error more gracefully

---

cypress/integration/unit_tests/add_layer_test.js
docs/import/add_layer.js
docs/import/color_function_util.js

#334
Test is sort of sad because jquery .hide() and .show() don't just toggle the hidden attr as I had expected. 
The matched elements will be hidden immediately, with no animation. This is roughly equivalent to calling .css( "display", "none" ), except that the value of the display property is saved in jQuery's data cache so that display can later be restored to its initial value. If an element has a display value of inline and is hidden then shown, it will once again be displayed inline.
https://api.jquery.com/hide/

Surface color editor immediately on layer add

---

cypress/integration/unit_tests/checkbox_test.js
cypress/integration/unit_tests/update_test.js
cypress/support/script_loader.js
docs/index.html
docs/update.js

update_test was using Promises but not actually waiting on them. This means it wasn't testing anything. In fact, there were three different failures visible in the console: 
I redid it as follows:
* Used cy.document(), which allows you to actually see the form being created. Also enables us to interact in the typical Cypress way with the elements.
* Simplified the assertions about the arguments to createAndDisplayJoinedData.
* Stubbed out showError, so we could directly assert on it rather than trying to fake the page out.
I found a real bug while doing this: we were calling createAndDisplayJoinedData even if there was an error validating the arguments. I also noticed that we didn't clear the error div. We should probably just get rid of that div and rely on the snackbar, but leaving that …

Revamp update_test

---

cypress/integration/unit_tests/manage_disaster_add_delete_test.js
docs/error.js
docs/import/manage_disaster.js

We just show a snackbar error. Not sure there's more we can do, because it's unexpected.
This will slightly slow down creation, because it's EE then Firestore, but worth it.
Also fix slightly broken test: under the covers we were creating states for the letters in 'IG, MY' because inputs can't have array values.
Closes #331

Handle EE folder creation errors and Firestore errors in disaster creation

---

docs/resources.js

Don't rename backup: if anything, we should make backup less attractive, so people don't try to create assets from it. Leaving that for another day. For now, it's alphabetically not that close to poverty-damage-score, so that's something.
I've already copied data-ms-as-tot over to poverty-damage-score for all of our disasters.
#335

Rename score asset to poverty-damage-score

---

cypress/integration/unit_tests/click_feature_test.js
docs/click_feature.js
docs/draw_table.js
docs/import/create_score_asset.js
docs/polygon_draw.js
docs/process_joined_data.js
docs/property_names.js
docs/run.js

Start to make map much more flexible. Instead of a hard-coded list of properties, since we're looping over the features anyway, keep track of their properties and display the ones we found. This will allow us to create a very generic score asset, with new properties we may never have considered, and display them on the map. In the limit, GD should be able to run score asset creation with a very general poverty asset.
Don't display absent properties in pop-up ("absent" now means, "absent from this feature, but present in other features"). I can't remember if we decided this was the preferred way to go, but I think it was. If we want to display '-', can modify to do that as well.
Make subtle change so that if damage tag is absent, will still do calculation properly. Can take advantage of …

Get properties of features dynamically, don't hard-code them

---

docs/update.js

Forgot to update the headers to be 'content-title' class, not form-title after making css changes to the mange pages, so the styling on the headers is gone. 
Screenshot with styling back on the first header, but not on the second:

Fix parameter headings to be content-title class

---

README.md
token_server/.elasticbeanstalk/config.yml
token_server/README.md
token_server/app.yaml
token_server/aws_get_credentials.js
token_server/ee_token_creator.js
token_server/package.json
token_server/token_server.js
token_server/yarn.lock

Main code change is that, because we're no longer running as a user that we can just give Google permissions to (the Google App Engine user), we have to store and load the credentials ourselves. The server can't do anything until that happens, so we wrap everything in the promise for that.
Other changes:
* AWS only supports Node 10 (boo) so had to drop down. Maybe they'll offer Node 12 soon: they offered 10 on [11/19/18](https://aws.amazon.com/about-aws/whats-new/2018/11/aws-elastic-beanstalk-adds-support-for-nodejs-10/), 20 days after Node 10 became the ["active" version](https://nodejs.org/en/about/releases/). Node 12 became the active version 10/21/19.
* Realized we were unnecessarily re-initializing auth and client objects inside ee_token_creator.js. Keep them around forever now.
* …

Add support to token server for AWS Elastic Beanstalk

---

docs/layer_util.js

This should be impossible, but since we have the error-handling code already, just call it.
#172

Get rid of impossible createError call by using existing error code

---

.travis.yml

I think I originally thought the first unsuccessful command would terminate Travis, and it would be annoying to not have the tests run because of a lint error. But apparently everything always runs, so faster commands should go first.

Lint before running tests

---

cypress/integration/unit_tests/color_function_util_test.js
cypress/integration/unit_tests/firebase_layers_test.js
docs/firebase_layers.js
docs/import/color_function_util.js
docs/run.js

Its location in import/ meant that the mapping page depended on import scripts, which shouldn't happen.

Move getLinearGradient to firebase_layers

---

cypress/integration/unit_tests/manage_disaster_set_score_parameters_test.js
cypress/integration/unit_tests/manage_layers_test.js
docs/import/manage_disaster.js
docs/import/manage_layers.js

In both manage_disaster and manage_layers it was doing a little bit, but not enough to justify keeping it: in manage_disaster, it helped us avoid a likely empty listing of the folder after creating a disaster, but actually in the edge case where a folder already existed, it could be incorrect. In manage_layers, it avoids creating a "pending" select that is immediately replaced by a real select, but the user doesn't actually see it, so it doesn't matter.
Fulfills https://github.com/givedirectly/Google-Partnership/pull/363#discussion_r361725663

Remove redundant disasterAssets map

---

cypress/integration/integration_tests/click_feature_test.js

Income is now a number, so Cypress doesn't weirdly include it in text.
Also changed score expectation, since that changed slightly.

Remove income string from expectation

---

cypress/integration/unit_tests/add_layer_test.js
cypress/integration/unit_tests/checkbox_test.js
cypress/integration/unit_tests/color_function_util_test.js
cypress/integration/unit_tests/firebase_layers_test.js
cypress/integration/unit_tests/manage_disaster_add_delete_test.js
cypress/integration/unit_tests/manage_layers_test.js
cypress/integration/unit_tests/process_joined_data_test.js
cypress/integration/unit_tests/style_functions_test.js
cypress/support/import_test_util.js
docs/README.md
docs/firebase_layers.js
docs/import/add_layer.js
docs/import/color_function_util.js
docs/import/create_disaster_lib.js
docs/import/manage_layers.js
docs/import/manage_layers_lib.js
docs/layer_util.js
docs/run.js

specifically:
asset-type -> assetType
ee-name -> eeName
display-name -> displayName
display-on-load -> displayOnLoad
color-function -> colorFunction
current-style -> currentStyle
and
layers -> layerArray

Convert all layer-related hyphenated vars to camelCase

---

admin_utils/process_firestore.js
cypress/integration/unit_tests/click_feature_test.js
cypress/integration/unit_tests/color_function_util_test.js
cypress/integration/unit_tests/create_score_asset_test.js
cypress/integration/unit_tests/manage_disaster_set_score_parameters_test.js
cypress/integration/unit_tests/polygon_draw_firebase_issues_test.js
cypress/integration/unit_tests/polygon_draw_test.js
cypress/integration/unit_tests/process_joined_data_test.js
cypress/integration/unit_tests/update_test.js
cypress/support/firestore_map_bounds.js
docs/click_feature.js
docs/create_map.js
docs/disaster_picker.js
docs/draw_table.js
docs/firestore_document.js
docs/import/create_disaster_lib.js
docs/import/create_score_asset.js
docs/navbar.js
docs/polygon_draw.js
docs/process_joined_data.js
docs/property_names.js
docs/run.js
docs/style.css
docs/update.js

* Write important parameters used to create score asset to Firestore. Move the old parameters if we're moving the asset, so it all stays in sync.
* Make score computation use parameters set when computing score asset, instead of hard-coded ones.
* We now know whether damage was actually used when creating score asset, versus just whether it exists now.
* Order columns according to some criteria (score -> poverty -> damage), and display in pop-up in that order as well. Also show "(data unavailable)" if a feature is missing data that other features have.
* Add a bunch of parameters to `assetData.flexibleData`, in preparation for follow-up PR. This allows user to customize the columns that are used for various things, and doesn't rename the columns, so that the user can see the original …

Allow for flexible columns when computing score

---

cypress/integration/unit_tests/polygon_draw_test.js
cypress/integration/unit_tests/update_test.js
docs/polygon_draw.js
docs/run.js
docs/update.js

Sequentializes things too much. User regions are still blocked, but there's a better reason for that.

Don't block layer loading on score asset retrieval

---

package.json
yarn.lock

Also pin all non-internet versions of our libraries to avoid any future forced upgrades.
I'd like to delete the `"nodeVersion": "system"` from our Cypress json because Cypress is now using Node 12, but unfortunately the Node version Cypress uses is an "electron" version, and gRPC, one of Firebase's binary dependencies, notices the incompatibility. Will continue investigating, because it would be nice for developers not to have to deal with node on their machines at all.
Closes #347

Upgrade Cypress

---

.travis.yml

If we get OSS plan up and running on dashboard, will revert this.

Stop recording Cypress runs on Travis in preparation for downgrading dashboard plan

---

docs/authenticate.js

This causes a new failure mode where the user has granted EarthEngine access but they're not whitelisted, which we also deal with.
Tested by going to accounts.google.com, revoking access for "Mapping disaster relief response," and visiting site.

Request proper access when first authenticating to app

---

cypress/integration/unit_tests/run_test.js
docs/run.js

Now that we wait for score asset existence before doing other operations, downloading the entire asset is an unnecessary block (even though we need to do it eventually). Race the download against a simpler EE query that should still succeed if the asset exists. This is both a performance optimization and a prerequisite for #437, which seems to slow down feature collection downloading in tests.

Speed up checking existence of score asset

---

cypress/integration/unit_tests/style_functions_test.js
docs/firebase_layers.js
docs/layer_util.js

Don't accidentally modify the color arrays.
I wonder if the latest deck.gl that we started using a few weeks before fellowship ended got stricter? It looks like this bug has been here since this code was introduced in #186.

Fix color rendering

---

docs/authenticate.js
token_server/token_server.js

Broken by https://github.com/givedirectly/Google-Partnership/commit/72dd1775cf549bec616f39a6467d73d3aaa2f42d#diff-10d6fe37a932cbb977d8ff39d67db610L203: we used to chain promises. When I switched to async style as part of EE upgrade, forgot to add "await" here.

Properly wait for response.json() promise

---

cypress/integration/integration_tests/checkbox_test.js
cypress/integration/unit_tests/manage_disaster_set_score_parameters_test.js
docs/import/manage_disaster_base.js
package.json
yarn.lock

This makes it easier to understand why an asset has an error. In real life, an asset had non-ascii characters in the column name, so add a specific check for that, because when the character is non-printable, it's impossible to tell with the naked eye why the name is wrong.

Augment error message when there are non-matching columns.
