givedirectly/Google-Partnership

- cypress/integration/unit_tests/center_test.js
- cypress/integration/unit_tests/polygon_draw_test.js
- cypress/support/script_loader.js
- docs/authenticate.js
- docs/create_map.js
- docs/firestore_document.js
- docs/import/center.js
- docs/import/import_data.html
- docs/import/import_data.js
- docs/polygon_draw.js
- docs/resources.js
- docs/script.js
Also let user know that map bounds calculation is in progress and when it completes. And add a unit test for center.js (first test of import functionality!).
First work on #175
> Fix center.js to use updated Firestore location for map bounds

- cypress/support/commands.js
Seeing some flaky failures on Travis, hoping this fixes them.
> Increase page loading timeout for tests

- package.json
Please let me know if you'd like a different license!
> Set project license to MIT

- docs/layer_util.js
Whoops. Will think about if testing is feasible in a follow-up.
> Fix redrawing score layer on update

- cypress/integration/unit_tests/add_disaster_test.js
- docs/import/add_disaster.html
- docs/import/add_disaster.js
- docs/import/add_disaster_startup.js
Add a button to cancel an add disaster process. Also disable and set the disaster picker to an option that just displays '...'.
> add cancel button

- docs/import/add_disaster.js
The combination of jquery and the optional parameter was doing something weird and globalWindow ended up being some event object. This fixes it.
> Fix delete button

- cypress/integration/unit_tests/add_disaster_test.js
- cypress/integration/unit_tests/polygon_draw_test.js
- docs/import/add_disaster.js
- docs/polygon_draw.js
- docs/popup.js
Turns out we can just use Cypress stubs. Who knew!
> Stub out window.confirm better

- cypress/integration/unit_tests/add_disaster_test.js
- docs/import/add_disaster.js
> Fix color boxes bug

- docs/fema_to_crowdai.html
- docs/import/import_data.html
- docs/index.html
- docs/navbar.html
- docs/navbar.js
- docs/style.css
They don't interact well with serving from a directory, which we do on github pages.
> Remove all absolute URL paths

- .travis.yml
- cypress/integration/integration_tests/polygon_draw_test.js
Not sure why it just started flaking, but I saw it in my pending PR and also on master when I ran it on my Mac.
> Fix failing test in polygon_draw_test

- .eslintrc.js
- cypress/integration/integration_tests/nav_test.js
- docs/authenticate.js
- docs/navbar.js
- docs/script.js
- package.json
- yarn.lock
And pull on some rather annoying strings: make more of our pages work with our test setup (of Firestore and EE tokens passed via cookies) by pushing the test branch into the new Authenticator static method, and change eslint a bit, because it doesn't like the "import.meta" tokens.
> Fix relative navbar loading issues

- docs/import/color_function_util.js
@janakdr suggested this a while back and I think it's the right move
> Highlight full row when clicking on color function

- cypress/integration/unit_tests/add_layer_test.js
- docs/import/add_layer.js
- docs/import/manage_layers.html
- docs/import/manage_layers.js
Will clean up if the overall approach is right.
> Prototype: add ui for non-ee layers

- cypress/integration/integration_tests/nav_test.js
- cypress/integration/integration_tests/polygon_draw_test.js
- cypress/plugins/index.js
With this, we can re-enable github status checks.
> Disable michael in tests

- docs/navbar.html
Not great, but better than nothing, I think?
> Add a basic link to the help doc in the navbar

- cypress/integration/integration_tests/nav_test.js
- cypress/integration/integration_tests/polygon_draw_test.js
- cypress/integration/unit_tests/polygon_draw_test.js
- cypress/plugins/index.js
We already had a unit test that was asserting almost everything we needed, so just assert a bit more.
> Fix up tests a bit: delete flaky polygon test, add back michael

- cypress/integration/integration_tests/nav_test.js
- cypress/integration/unit_tests/polygon_draw_test.js
- docs/polygon_draw.js
> Include total households in popup

- cypress/plugins/index.js
- cypress/support/script_loader.js
- docs/authenticate.js
- docs/firestore_document.js
- docs/in_test_util.js
The latter is only usable locally, so it's clearer this is all client-side.
> Replace usage of cookies with window.localStorage

- cypress/integration/unit_tests/click_feature_test.js
- docs/draw_table.js
> Fix bug in clicking feature when feature not in list

- cypress/integration/unit_tests/create_score_asset_test.js
- docs/import/create_score_asset.js
Try a rename, if it fails because the backup was present, then delete, then try the rename again.
#306
> Don't delete backup asset unless we have to

- cypress/integration/unit_tests/add_layer_test.js
- docs/ee_paths.js
- docs/import/add_layer.js
> Set EE asset to world readable when added as a layer

- docs/import/manage_disaster.css
> Increase size and font size of process button

- cypress/integration/unit_tests/manage_disaster_set_score_parameters_test.js
- docs/import/list_ee_assets.js
- docs/import/manage_disaster.js
We don't need it anymore under the covers, so simplifies code.
Also get rid of stray `.only`.
> Get rid of looking states up in batches

- cypress/integration/unit_tests/manage_disaster_add_delete_test.js
- docs/import/manage_disaster.js
Disasters can share states, and if a disaster folder is created as part of an unsuccessful add (say because Firestore write failed), we want to be able to re-use it.
Also fix bug where we were writing locally before EE and Firestore succeeded, so failures left the page in a bad state. We actually had test coverage for this, but Cypress apparently has a bug.
Main bug here was introduced by #361: we added error handling there, but didn't tolerate "already existing" errors. I had thought in the back of my mind that overwrite=false would prevent errors, but didn't actually test it.
> Fix bug where we errored if folder already existed

- docs/click_feature.js
> Display an error to user if click fails

- docs/update.js
Come good on overdue request from https://github.com/givedirectly/Google-Partnership/pull/318#discussion_r358493030.
> Some style cleanups for update.js

- admin_utils/process_firestore.js
- lint.sh
Ran this in order to enable #390. Seems worth having in the repo for future needs.
> Add script used to migrate keys to camel case

- cypress/integration/unit_tests/polygon_draw_test.js
Failed two times in a row for me, but pretty hard to reproduce. Think this fixed it, we'll see.
> Try to deflake new test

- docs/import/manage_disaster.html
- docs/import/manage_disaster.js
Adding some spacing between elements and hiding the Create Disaster button if we're already in that flow.
> Basic ui updates to create disaster page

- docs/import/manage_layers.js
Not sure writing a test is worth it but lmk
> Fix bug where color editor stayed up when switching disasters

- docs/authenticate.js
> Updating maintainer email address 

- cypress/integration/unit_tests/click_feature_test.js
- docs/click_feature.js
> Fix pop-up

- cypress/integration/unit_tests/color_function_util_test.js
- cypress/integration/unit_tests/firebase_layers_test.js
- cypress/integration/unit_tests/manage_disaster_set_score_parameters_test.js
- cypress/integration/unit_tests/manage_layers_test.js
- docs/firebase_layers.js
- docs/import/color_function_util.js
- docs/import/manage_disaster.js
- docs/polygon_draw.js
- docs/run.js
Greens weren't matching up before. I also am not clear how createCheckboxForUserFeatures was working before, so updated. 
Now that layer green is very similar to the green of user features, make user features a nice cyan ('#00FFFF')
> Always use rgb values for colors 

- docs/default_disaster.js
- docs/resources.js
@ruthtalbot not sure where documentation should go for this. I documented lightly in file but I figure more extensive docs will have to live somewhere else
> factor out default disaster to standalone file for easy access

- docs/authenticate.js
- docs/owner.js
- token_server/origins.js
- token_server/token_server.js
> Factor out code references to GD to a standalone file

- docs/import/manage_disaster.html
- docs/import/manage_layers.html
- docs/style.css
> Unifying styles for status divs on manage pages

- cypress/integration/unit_tests/polygon_draw_firebase_issues_test.js
- cypress/support/script_loader.js
- docs/ee_test.html
Also sneak a test flakiness fix in.
> Make debugging page a little friendlier

- docs/import/upload_image_collection.html
- docs/import/upload_image_collection.js
- docs/import/upload_image_collection_startup.js
> Improve image collection upload page UI

- docs/import/manage_disaster.html
- docs/import/manage_disaster.js
- docs/import/manage_disaster_flexible.js
- docs/import/manage_disaster_state_based.js
- docs/import/manage_layers.html
- docs/import/manage_layers.js
- docs/import/manage_layers_startup.js
- docs/style.css
> Adding loading overlays

- .travis.yml
> Got OSS plan, record again

- docs/composite_image_map_type.js
This avoids ugly "broken image" icons like
Do a belt-and-suspenders fix to also hide the image if it is in error. That seems less brittle to me than examining the type of the downloaded blob, but unfortunately it causes flickering since the image renders broken and only then gets hidden.
Also fix a minor bug (probably introduced in https://github.com/givedirectly/Google-Partnership/pull/437) that caused the loading indicator overlay to be prematurely removed and then never added back.
Not adding tests in the interests of expediency and also I think tests might be broken right now.
> Drop "404" error pages when fetching image tiles
